name: Build and Lint

on: 
  - push
  - pull_request

jobs:
  CI:

    runs-on: macos-10.15

    steps:
    - uses: actions/checkout@v2

    - name: Prepare Env
      run: |
        sudo xcode-select -s "/Applications/Xcode_12.2.app"
        pod install

    - name: Check Strings
      run: |
        for file (./HeliPort/Appearance/**/*.strings) {
          plutil -lint $file
          if [[ $file != *"zh-Hans"* ]]; then
            grep -Hn "：" $file >> /tmp/chnCol.txt
          fi
        }
        echo ""
        if [[ $(cat /tmp/chnCol.txt) != "" ]]; then
          echo "ERROR!!! Chinese Colon\"：\" exists in:"
          echo ""
          cat /tmp/chnCol.txt
          exit 1
        fi
      shell: zsh {0}

    - name: SwiftLint
      run: |
        function stripPWD() {
          sed -E "s/$(pwd|sed 's/\//\\\//g')\///"
        }

        function convertToGitHubActionsLoggingCommands() {
          sed -E 's/^(.*):([0-9]+):([0-9]+): (warning|error|[^:]+): (.*)/::\4 file=\1,line=\2,col=\3::\5/'
        }

        set -o pipefail && swiftlint | stripPWD | convertToGitHubActionsLoggingCommands

    - name: Debug Build
      run: |
        xcodebuild -workspace HeliPort.xcworkspace -scheme HeliPort -configuration Debug -derivedDataPath build CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty && exit ${PIPESTATUS[0]}
